version: '3.8'

services:
  kafka:
    image: bitnami/kafka:latest
    container_name: kafka
    ports:
      - "9092:9092"

    environment:
      # KRaft 模式配置
      KAFKA_CFG_NODE_ID: "0"
      KAFKA_CFG_PROCESS_ROLES: "controller,broker"
      KAFKA_CFG_CONTROLLER_LISTENER_NAMES: "CONTROLLER"
      KAFKA_CFG_CONTROLLER_QUORUM_VOTERS: "0@kafka:9094"

      # 监听器配置
      # 9093 用于容器内部通信
      # 9092 用于电脑主机通信
      KAFKA_CFG_LISTENERS: "INTERNAL://:9093,EXTERNAL://:9092,CONTROLLER://:9094"
      KAFKA_CFG_ADVERTISED_LISTENERS: "INTERNAL://kafka:9093,EXTERNAL://localhost:9092"
      KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP: "CONTROLLER:PLAINTEXT,INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT"
      KAFKA_CFG_INTER_BROKER_LISTENER_NAME: "INTERNAL"

      # 允许自动创建 Topic
      KAFKA_CFG_AUTO_CREATE_TOPICS_ENABLE: "true"
      KAFKA_CFG_NUM_PARTITIONS: "3"

  mongo:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"
    # restart 意思是无论容器退出状态如何，都会自动重启容器
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: "admin"
      MONGO_INITDB_ROOT_PASSWORD: "admin"
    volumes:
        - /app/data/mongo:/data/db
